[theme]
primaryColor="#00a19c"
backgroundColor="#efebeb"
secondaryBackgroundColor="#cfced0"
textColor="#20419a"

[client]
showErrorDetails = true
showSidebarNavigation = true
toolbarMode = "developer"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[server]
headless = true
port = 8501
runOnSave = true
